# Generated by Django 4.0.6 on 2022-09-10 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='con',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('address', models.CharField(max_length=200)),
                ('phone', models.IntegerField()),
                ('comments', models.CharField(max_length=500)),
            ],
        ),
    ]
